//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AkiToyWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserva
    {
        public int idReserva { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<int> idProducto { get; set; }
        public Nullable<int> idCliente { get; set; }
        public Nullable<int> idPago { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Pago Pago { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
